# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmt" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "b7b90328419bbb8d575b421ebfd06664ca2c1e92e4c3929fd9b21fd1bf8aa484"
      url "https://github.com/yarlson/cmt/releases/download/v#{version}/cmt_Darwin_x86_64.tar.gz",
        verified: "github.com/yarlson/cmt/"
    end
    on_arm do
      sha256 "894b7379568df05aff3f3d90da006f9f4ec9ce123a6571afd09a1c881d60d277"
      url "https://github.com/yarlson/cmt/releases/download/v#{version}/cmt_Darwin_arm64.tar.gz",
        verified: "github.com/yarlson/cmt/"
    end
  end

  on_linux do
    on_intel do
      sha256 "1f05e17dfb4f4ed8aa628d6f80a1850c7e942937c85c5ab34654105daf56c5db"
      url "https://github.com/yarlson/cmt/releases/download/v#{version}/cmt_Linux_x86_64.tar.gz",
        verified: "github.com/yarlson/cmt/"
    end
    on_arm do
      sha256 "bd7377495e5c2b56144c37f0d3f68cfb6e9861dae85eb7e8136ea3438c83e36f"
      url "https://github.com/yarlson/cmt/releases/download/v#{version}/cmt_Linux_arm64.tar.gz",
        verified: "github.com/yarlson/cmt/"
    end
  end

  name "cmt"
  desc "Generate meaningful git commit messages with Claude Code"
  homepage "https://github.com/yarlson/cmt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmt"

  # No zap stanza required

end
