# This file was generated by GoReleaser. DO NOT EDIT.
cask "lgtm" do
  name "lgtm"
  desc "lgtm is an AI coding agent harness that plugs into Claude Code or OpenCode to implement your ideas. It generates a PRD, breaks it into tasks, implements each with TDD, reviews its own code, fixes issues, and commits. You review the final result."
  homepage "https://github.com/yarlson/lgtm"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lgtm"

  on_macos do
    on_intel do
      url "https://github.com/yarlson/lgtm/releases/download/v#{version}/lgtm_#{version}_Darwin_x86_64.tar.gz"
      sha256 "2bfeac9edd9d98e8eba051bbdae5194fe49444dbbcceb40b506f6ec6f143099e"
    end
    on_arm do
      url "https://github.com/yarlson/lgtm/releases/download/v#{version}/lgtm_#{version}_Darwin_arm64.tar.gz"
      sha256 "02275c8326310fca260adeff9ab65db3555ff29e8f21e3967c514db149c46bb6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yarlson/lgtm/releases/download/v#{version}/lgtm_#{version}_Linux_x86_64.tar.gz"
      sha256 "5d1e71485cd9e3cd47f0e07f87a24cd45cded2647399aaf2a6714da10f8b54a9"
    end
    on_arm do
      url "https://github.com/yarlson/lgtm/releases/download/v#{version}/lgtm_#{version}_Linux_arm64.tar.gz"
      sha256 "7b810abd5e1bc93f36e2726b34439a82f99fbd6f110f9518e363b022fbd6cf06"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lgtm"]
    end
  end

  # No zap stanza required
end
