# This file was generated by GoReleaser. DO NOT EDIT.
cask "mokapot" do
  name "mokapot"
  desc "Local AWS mock. One binary, zero credentials."
  homepage "https://github.com/yarlson/mokapot"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mokapot"

  on_macos do
    on_intel do
      url "https://github.com/yarlson/mokapot/releases/download/v#{version}/mokapot_#{version}_darwin_amd64.tar.gz"
      sha256 "1f3feac25b5544e8dae07fa86c596ee4f4314d91cd9dead8e5b19c96232ae201"
    end
    on_arm do
      url "https://github.com/yarlson/mokapot/releases/download/v#{version}/mokapot_#{version}_darwin_arm64.tar.gz"
      sha256 "497cdcacd65ce7e1d4ed601b45e8a72e972cc08c06bf48fad0816f05a9e52d81"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yarlson/mokapot/releases/download/v#{version}/mokapot_#{version}_linux_amd64.tar.gz"
      sha256 "e3f22180dfcd45a6cf307b41b920b6ed01bd040e4878cfe65d56e0f2e95039cd"
    end
    on_arm do
      url "https://github.com/yarlson/mokapot/releases/download/v#{version}/mokapot_#{version}_linux_arm64.tar.gz"
      sha256 "9a37b68c2f657edfb3249b1df181b5309f89344d94e060d9639b94402ca70408"
    end
  end

  # No zap stanza required
end
