# This file was generated by GoReleaser. DO NOT EDIT.
cask "scr" do
  name "scr"
  desc "Automated terminal screenshots. Script interactions, capture PNGs."
  homepage "https://github.com/yarlson/scr"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scr"

  on_macos do
    on_intel do
      url "https://github.com/yarlson/scr/releases/download/v#{version}/scr_#{version}_Darwin_x86_64.tar.gz"
      sha256 "dcaed9c672fc9fab801d97ea79ef52876a0004a0fc82073688bb122a411cca27"
    end
    on_arm do
      url "https://github.com/yarlson/scr/releases/download/v#{version}/scr_#{version}_Darwin_arm64.tar.gz"
      sha256 "60f907d5605ca52c5c578ec7b512a87d9f43cfd3df384cfcf9e2960f27cc0d14"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yarlson/scr/releases/download/v#{version}/scr_#{version}_Linux_x86_64.tar.gz"
      sha256 "d82616e3e0bf16433bc8ed98555b09719bad04823d1f2e4287e83fc99d117f8c"
    end
    on_arm do
      url "https://github.com/yarlson/scr/releases/download/v#{version}/scr_#{version}_Linux_arm64.tar.gz"
      sha256 "b369fa0ae14db4357f7aa1dddc7a581da99a816cf76ba615fd737c66223e0967"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scr"]
    end
  end

  # No zap stanza required
end
