# This file was generated by GoReleaser. DO NOT EDIT.
cask "scr" do
  name "scr"
  desc "Automated terminal screenshots. Script interactions, capture PNGs."
  homepage "https://github.com/yarlson/scr"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scr"

  on_macos do
    on_intel do
      url "https://github.com/yarlson/scr/releases/download/v#{version}/scr_#{version}_Darwin_x86_64.tar.gz"
      sha256 "ecc6b57bf06a21299c2a5c4eddc2a740a14687694b1fe37820f689b68fecf5ae"
    end
    on_arm do
      url "https://github.com/yarlson/scr/releases/download/v#{version}/scr_#{version}_Darwin_arm64.tar.gz"
      sha256 "f8ae0b9f744193cbe5489326639198c973e7e70368c256557292e419a0ae2aea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yarlson/scr/releases/download/v#{version}/scr_#{version}_Linux_x86_64.tar.gz"
      sha256 "94d6dc64551fb0003690e96aa17793cdbc8a3ad3393c60fca615b7bd745dae3f"
    end
    on_arm do
      url "https://github.com/yarlson/scr/releases/download/v#{version}/scr_#{version}_Linux_arm64.tar.gz"
      sha256 "ab8b2c27717a4d41dff9dfbef1b791409703d8ca994a6f31c527216daa356a24"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scr"]
    end
  end

  # No zap stanza required
end
