# This file was generated by GoReleaser. DO NOT EDIT.
cask "ship" do
  name "ship"
  desc "Transfer a local Docker image to a remote host over SSH."
  homepage "https://github.com/yarlson/ship"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ship"

  on_macos do
    on_intel do
      url "https://github.com/yarlson/ship/releases/download/v#{version}/ship_#{version}_darwin_amd64.tar.gz"
      sha256 "9289a2e1aaf4b74904bc31af476ed92fb687c2ade77daa2026cdc44fc6ffe52c"
    end
    on_arm do
      url "https://github.com/yarlson/ship/releases/download/v#{version}/ship_#{version}_darwin_arm64.tar.gz"
      sha256 "d8084cfd29368334ccdef414522973960bec3f0eb95e6a8dcabcb30d515f45ed"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yarlson/ship/releases/download/v#{version}/ship_#{version}_linux_amd64.tar.gz"
      sha256 "5a360f8d5f0db7e0c8cddbd20d54f9e8a97acc3b2de0da6084b56eb534d17f14"
    end
    on_arm do
      url "https://github.com/yarlson/ship/releases/download/v#{version}/ship_#{version}_linux_arm64.tar.gz"
      sha256 "1117a992edc2c537a093e5c75b1e2c79fcee95ea1d9430e0677ffd69a1368bdd"
    end
  end

  # No zap stanza required
end
