# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmt < Formula
  desc "Generate meaningful git commit messages with Claude Code"
  homepage "https://github.com/yarlson/cmt"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yarlson/cmt/releases/download/v0.9.0/cmt_Darwin_x86_64.tar.gz"
      sha256 "c2fdd8f72a39fa7054a9f1e970f35ee993bf0950dda9d595e41b3c93a6bbe9f4"

      define_method(:install) do
        bin.install "cmt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yarlson/cmt/releases/download/v0.9.0/cmt_Darwin_arm64.tar.gz"
      sha256 "17df4d8095450e29a64101c21f7f7bc8f41d9c63299d24dd73e04b9859687e04"

      define_method(:install) do
        bin.install "cmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/cmt/releases/download/v0.9.0/cmt_Linux_x86_64.tar.gz"
      sha256 "380431ba8ceb83da5d31dbf3a477f00e6ed2b93549a088b5484fac72260a5558"
      define_method(:install) do
        bin.install "cmt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/cmt/releases/download/v0.9.0/cmt_Linux_arm64.tar.gz"
      sha256 "06140fd176c485f3a77f825d0e86c94f71b9c4315fb3309f4c51d1e2d3baec52"
      define_method(:install) do
        bin.install "cmt"
      end
    end
  end

  test do
    system "#{bin}/cmt --version"
  end
end
