# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmt < Formula
  desc "Generate meaningful git commit messages with Claude Code"
  homepage "https://github.com/yarlson/cmt"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yarlson/cmt/releases/download/v0.7.0/cmt_Darwin_x86_64.tar.gz"
      sha256 "816a7a3fee7987f0c56ca23a04c7d8d1a5ed64f3719a30d3ee3960b7fef87744"

      define_method(:install) do
        bin.install "cmt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yarlson/cmt/releases/download/v0.7.0/cmt_Darwin_arm64.tar.gz"
      sha256 "f4d27f304cb5c24b279d40bc7cac61776467d3111909cc6a85cc282bbc9d1b02"

      define_method(:install) do
        bin.install "cmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/cmt/releases/download/v0.7.0/cmt_Linux_x86_64.tar.gz"
      sha256 "471c280e9d7503b28910d8001044bd0ed5ae94a3d2b85ba9d74652e95676df8f"
      define_method(:install) do
        bin.install "cmt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/cmt/releases/download/v0.7.0/cmt_Linux_arm64.tar.gz"
      sha256 "b7f3445f9086a30edd703a1707740f3c265ba69c40f2e606d49b38b85656e1c7"
      define_method(:install) do
        bin.install "cmt"
      end
    end
  end

  test do
    system "#{bin}/cmt --version"
  end
end
