# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ship < Formula
  desc "Transfer local Docker images to a remote host over SSH."
  homepage "https://github.com/yarlson/ship"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yarlson/ship/releases/download/v0.2.3/ship_0.2.3_darwin_amd64.tar.gz"
      sha256 "4db4321535cb191b50555140e2f9a802e7ead258e0b84c4c23b26912d06d2a1a"

      define_method(:install) do
        bin.install "ship"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yarlson/ship/releases/download/v0.2.3/ship_0.2.3_darwin_arm64.tar.gz"
      sha256 "82d4d3f1827eb94b82bc838416481a45bebfe6f1cfb4674c864614ad198e29e6"

      define_method(:install) do
        bin.install "ship"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/ship/releases/download/v0.2.3/ship_0.2.3_linux_amd64.tar.gz"
      sha256 "5962e26318f14891fd17f4bad710b106ec2623b7f8b61919962606b6f12787ca"
      define_method(:install) do
        bin.install "ship"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/ship/releases/download/v0.2.3/ship_0.2.3_linux_arm64.tar.gz"
      sha256 "c01775a8b6ecab25acb3c912f870834239a9015b358aae0b74b8f896f36852a0"
      define_method(:install) do
        bin.install "ship"
      end
    end
  end
end
